language: node_js

node_js:
  - node
  - '12.20.0'

cache: npm
    
jobs:
  include:
    - stage: "Unit Tests"                
      name: "Unit Tests"           
      script: npm test
  
    
    - stage: "Test CI"
      name: "coveralls Tests"
      script: npm run test:ci
